Repository zeabur/cli, pull requests merged in 2024-01, with the labels that each got.

#57 feat: deploy prebuilt services
  internal/cmd/service/deploy/deploy.go
  pkg/api/interface.go
  pkg/api/service.go
  pkg/model/service.go
Labels: enhancement

#58 Feat/create domain
  go.mod
  go.sum
  internal/cmd/deploy/deploy.go
  internal/cmd/service/domain/domain.go
  pkg/api/interface.go
  pkg/api/service.go
  pkg/model/domain.go
Labels: enhancement

#59 fix: ignore files in gitignore patterns
  internal/util/pack.go
Labels: enhancement

#60 ZEA-2387: Fix cli OAuth login 401 error
  pkg/auth/client.go
Labels: bug

#63 refactor/deploy
  internal/util/pack.go
  zeabur.zip
Labels: improvement

#64 ZEA-2471: Fix cli refresh token logic
  internal/cmd/root/root.go
Labels: bug

#65 ZEA-2466: Add release update check
  go.mod
  go.sum
  internal/cmd/root/release.go
  internal/cmd/root/root.go
  internal/cmdutil/factory.go
  pkg/config/config.go
Labels: enhancement

#70 fix: service metric for memory and cpu
  internal/cmd/service/metric/metric.go
  pkg/api/interface.go
  pkg/api/service.go
  pkg/model/service.go
Labels: bug

#69 ZEA-2475: Bind domain in cli
  internal/cmd/domain/create/create.go
  internal/cmd/domain/domain.go
  internal/cmd/root/root.go
  internal/cmd/service/domain/domain.go
  internal/cmd/service/service.go
  pkg/api/domain.go
  pkg/api/interface.go
  pkg/api/service.go
  pkg/model/domain.go
Labels: enhancement

#73 ZEA-2480: Implement list/delete domain
  internal/cmd/domain/create/create.go
  internal/cmd/domain/delete/delete.go
  internal/cmd/domain/domain.go
  internal/cmd/domain/list/list.go
  pkg/api/domain.go
  pkg/api/interface.go
  pkg/model/domain.go
Labels: enhancement

#74 ZEA-2482: Implement better ui for domain list cmd
  pkg/model/domain.go
  pkg/printer/printer.go
  pkg/util/time.go
Labels: enhancement

#75 ZEA-2484: Time display optimization
  pkg/model/deployment.go
  pkg/model/project.go
  pkg/model/service.go
  pkg/model/template.go
  pkg/model/user.go
Labels: enhancement

#76 feat: get instructions
  internal/cmd/service/instruction/instruction.go
  internal/cmd/service/service.go
  pkg/api/interface.go
  pkg/api/service.go
  pkg/model/service.go
Labels: enhancement

#77 ZEA-2509: Environment variables support
  internal/cmd/root/root.go
  internal/cmd/variable/create/create.go
  internal/cmd/variable/delete/delete.go
  internal/cmd/variable/list/list.go
  internal/cmd/variable/update/update.go
  internal/cmd/variable/variable.go
  pkg/api/common.go
  pkg/api/interface.go
  pkg/api/variable.go
  pkg/model/variable.go
Labels: enhancement

#78 ZEA-2510: Internal network output
  internal/cmd/service/network/network.go
  internal/cmd/service/service.go
  pkg/api/interface.go
  pkg/api/service.go
Labels: enhancement

#79 fix: version compare bug
  internal/cmd/root/release.go
Labels: bug

#80 fix(selector/service): Fix cli deploy auto select service
  .gitignore
  internal/cmd/context/set/set.go
  internal/cmd/deploy/deploy.go
  pkg/fill/fill.go
  pkg/selector/selector.go
Labels: bug

#81 fix(util/pack): Fix code upload deploy zip error
  internal/util/pack.go
  pkg/api/service.go
Labels: bug

#83 feat: Add pr issue template & code_of_conduct doc
  .github/ISSUE_TEMPLATE/BugReport.yml
  .github/ISSUE_TEMPLATE/Documentation.yml
  .github/ISSUE_TEMPLATE/FeatureRequest.yml
  .github/ISSUE_TEMPLATE/Style.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation, enhancement
